<?php

namespace Nav\WunderlistBundle\Repository;

/**
 * WunderlistListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WunderlistListRepository extends \Doctrine\ORM\EntityRepository
{
}
