<?php

namespace Nav\WunderlistBundle\Repository;

/**
 * WunderlistAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WunderlistAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
