<?php

namespace Nav\WunderlistBundle\Repository;

/**
 * WunderlistTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WunderlistTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
