parameters:
    wunderlist.clientid: "YOUR-WUNDERLIST-CLIENT-ID"
    wunderlist.clientsecret: "YOUR-WUNDERLIST-SECRET"
    wunderlist.baseurl: "https://a.wunderlist.com/"

services:
    nav_wunderlist.client:
        class: Nav\WunderlistBundle\Client\Wunderlist
        arguments: ["@service_container", "@request_stack"]

    nav_wunderlist.tasks:
        class: Nav\WunderlistBundle\Client\WunderlistTasks
        arguments: ["@service_container", "@doctrine.orm.default_entity_manager"]